server:
  port: 9001
spring:
  application:
    name: uqChat-query
  cloud:
    nacos:
      discovery:
        server-addr: http://47.104.151.120:8848
        service: ${spring.application.name}
  datasource:
    username: root
    password: 960407yzD
#    url: jdbc:mysql://192.168.124.128:3306/demoData?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://rm-m5e9it74k7r821a4tzo.rwlb.rds.aliyuncs.com/uq_data?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 35000


feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间,
        connect-timeout: 5000
        #指建立连接后从服务端读取到可用资源所用的时间,默认为1s
        read-timeout: 5000
